[toolchain]

[features]
resolution = false
seeds = false
skip-lint = false

[programs.devnet]
solana_c_nft = "EFijqZMBdgdqeHYiTDtuk3xuHt2j8wnyUTvubARYoA34"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = '/mnt/c/Users/Axel/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solana-c-nft.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/token_metadata.so"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "./deps/bubblegum.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "./deps/spl_noop.so"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "./deps/spl_account_compression.so"